# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: api-testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run TestProject Agent
      env:
        TP_API_KEY: ${{ secrets.TP_API_KEY }}
      run: |
        envsubst < .github/CI/docker-compose.yml > docker-compose.yml
        docker-compose -f docker-compose.yml up -d
    - name: Wait for Agent to Register
      run: bash .github/CI/wait_for_agent.sh
    - name: Test with pytest
#      run: coverage run tests/test_main_page.py tests/test_product_page.py
      run: pytest 
      env:
        TP_DEV_TOKEN: ${{ secrets.TP_DEV_TOKEN }}
        TP_AGENT_URL: http://localhost:8585
